### ISSUE TITLE
curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by IceClear** [zhkmxx9302013/BUAA_AutoLogin#1]

**Comment by zhkmxx9302013** [comment]
您的设备需要搞一个CA证书，参考这里
[修复 SSL certificate problem: unable to get local issuer certificate](http://blog.kankanan.com/article/4fee590d-ssl-certificate-problem-unable-to-get-local-issuer-certificate.html)
